[package]
name = "aoc2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoclib = { path = "../aoclib" }
itertools = "0.13.0"
md5 = "0.7.0"
lazy_static = "1.4"
regex = "1"
substring = "1"
